config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  validates :name, :sku, presence:true
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  validates :corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email, presence:true
  has_many :suppliers
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
    validates :name, :code, :city, :description, :address, :zip_code, :area, presence: true
    validates :name, :code, uniqueness: true
    validates :zip_code, format: {with: /\A\d{5}-\d{3}\Z/}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @warehouses=Warehouse.all
    end
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
  def index
    @product_models = ProductModel.all
  end

  def new
    @product_model = ProductModel.new
    @suppliers = Supplier.all
  end

  def create
    product_model_params = params.require(:product_model).permit(:name, :weight, :width, :height, :depth, :sku, :supplier_id)
    
    @product_model = ProductModel.new(product_model_params)
    
    if @product_model.save
      redirect_to @product_model, notice:'Modelo de Produto cadastrado com sucesso.'
    else
      @suppliers = Supplier.all
      flash.now[:notice] = 'Não foi possível cadastrar o modelo de produto.'
      render 'new'
    end
  end

  def show
    @product_model = ProductModel.find(params[:id])
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  def index
    @suppliers = Supplier.all
  end

  def show
    @supplier = Supplier.find(params[:id])
  end

  def new
    @supplier = Supplier.new
  end

  def create
    supplier_params = params.require(:supplier).permit(:corporate_name, :brand_name, :city, :registration_number, 
                                     :full_address, :state, :email)
    @supplier=Supplier.new(supplier_params)

    if @supplier.save()
      redirect_to @supplier, notice:'Fornecedor cadastrado com sucesso.'
    else
      flash.now[:notice]='Fornecedor não cadastrado.'
      render 'new'
    end
  end

  def edit
    @supplier = Supplier.find(params[:id])
  end

  def update
    @supplier = Supplier.find(params[:id])
    supplier_params = params.require(:supplier).permit(:corporate_name, :brand_name, :city, :registration_number, 
                                     :full_address, :state, :email)
    if @supplier.update(supplier_params)
      redirect_to supplier_path(@supplier.id), notice: 'Fornecedor atualizado com sucesso.'
    else
      flash.now[:notice] = 'Não foi possível atualizar o fornecedor.'
      render 'edit'
    end                                      
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
    before_action :set_warehouse, only: [:show, :edit, :update, :destroy]

    def show; end

    def new 
        @warehouse=Warehouse.new
    end

    def create
        @warehouse=Warehouse.new(warehouse_params)
            
       if @warehouse.save()
        redirect_to root_path, notice:'Galpão cadastrado com sucesso.'
       else
        flash.now[:notice]='Galpão não cadastrado.'
        render 'new'
       end
    end

    def edit; end

    def update
        warehouse_params
        if @warehouse.update(warehouse_params)
            redirect_to warehouse_path(@warehouse.id), notice: 'Galpão atualizado com sucesso.'
        else
            flash.now[:notice] = 'Não foi possível atualizar o galpão.'
            render 'edit'
        end                                      
    end

    def destroy  
        @warehouse.destroy
        redirect_to root_path, notice: 'Galpão removido com sucesso.'
    end

    private

    def set_warehouse
        @warehouse = Warehouse.find(params[:id])
    end

    def warehouse_params
        params.require(:warehouse).permit(:name, :code, :city, :description, 
                                          :address, :zip_code, :area)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<p>
  <%=I18n.localize(Date.today)%>
</p>

<section id='warehouses'>
    <h2>Galpões</h2>
    <div>
        <%=link_to('Cadastrar Galpão', new_warehouse_path)%>
    </div>
    <%@warehouses.each do |w|%>
        <div>
            <h3><%=link_to(w.name, warehouse_path(w.id))%></h3>
            <dl>
                <dt>Código: </dt>
                <dd><%=w.code%></dd>
                <dt>Cidade: </dt>
                <dd><%=w.city%></dd>
                <dt>Área: </dt>
                <dd><%=w.area%> m²</dd>
            </dl>
        </div>
    <%end%>

    <%if @warehouses.empty?%>
        <p>Não existem galpões cadastrados.</p>
    <%end%>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp - Criado por Campus Code</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <h1>Galpões & Estoque</h1>
      <nav>
        <%=link_to 'Fornecedores', suppliers_path%>
        <%=link_to 'Modelos de Produtos', product_models_path%>
      </nav>
    </header>
    <main>
      <div>
          <%=notice%>
      </div>
      <%= yield %>
    </main>
  </body>
</html>

app/views/product_models/index.html.erb
<h1>Modelos de Produtos</h1>

<%= link_to 'Cadastrar Novo', new_product_model_path%>
<%if @product_models.any?%>
  <%@product_models.each do |pm|%>
    <div>
      <h2><%= pm.name%></h2>
      <dl>
        <dt>SKU</dt>
        <dd><%= pm.sku%></dd>
        <dt>Fornecedor</dt>
        <dt><%= pm.supplier.brand_name%></dt>
      </dl>
    </div>
  <%end%>
<%else %>  
  <p>Nenhum modelo de produto cadastrado.</p>
<%end%>

app/views/product_models/new.html.erb
<h1>Novo Modelo de Produtos</h1>

<%=form_with(model: @product_model) do |f|%>
    <div>
        <%=f.label :name%>
        <%=f.text_field :name%>
    </div>
    <div>
        <%=f.label :weight%>
        <%=f.number_field :weight%>
    </div>
    <div>
        <%=f.label :width%>
        <%=f.number_field :width%>
    </div>
    <div>
        <%=f.label :height%>
        <%=f.number_field :height%>
    </div>
    <div>
        <%=f.label :depth%>
        <%=f.number_field :depth%>
    </div>
    <div>
        <%=f.label :sku%>
        <%=f.text_field :sku%>
    </div>
    <div>
        <%=f.label :supplier_id%>
        <%=f.collection_select :supplier_id, @suppliers, :id, :brand_name%>
    </div>
    <div>
        <%=f.submit 'Enviar'%>
    </div>
<%end%>

app/views/product_models/show.html.erb
<h1><%= @product_model.name%></h1>

<dl>
  <dt>Fornecedor: </dt>
  <dd><%= @product_model.supplier.brand_name %></dd>
  <dt>SKU: </dt>
  <dd><%= @product_model.sku %></dd>
  <dt>Peso: </dt>
  <dd><%= @product_model.weight %>g</dd>
  <dt>Dimensões: </dt>
  <dd><%= @product_model.height %>cm x <%= @product_model.width%>cm x <%= @product_model.depth %>cm</dd>
</dl>

app/views/suppliers/edit.html.erb
<h1>Editar Fornecedor</h1>

<%=form_with(model: @supplier) do |f|%>
    <div>
        <%=f.label :corporate_name%>
        <%=f.text_field :corporate_name%>
    </div>
    <div>
        <%=f.label :brand_name%>
        <%=f.text_field :brand_name%>
    </div>
    <div>
        <%=f.label :registration_number%>
        <%=f.text_field :registration_number%>
    </div>
    <div>
        <%=f.label :full_address%>
        <%=f.text_field :full_address%>
    </div>
    <div>
        <%=f.label :city%>
        <%=f.text_field :city%>
    </div>
    <div>
        <%=f.label :state%>
        <%=f.text_field :state%>
    </div>
    <div>
        <%=f.label :email%>
        <%=f.text_field :email%>
    </div>
    <div>
        <%=f.submit 'Enviar'%>
    </div>
<%end%>

app/views/suppliers/index.html.erb
<section id='suppliers'>
    <h2>Fornecedores</h2>

    <%@suppliers.each do |s|%>
      <%= link_to s.brand_name, s%>
      <%= s.city%> - <%= s.state%>
    <%end%>

    <%if @suppliers.empty?%>
        <p>Não existem fornecedores cadastrados.</p>
    <%end%>

    <%= link_to 'Cadastrar fornecedor', new_supplier_path%>
</section>

app/views/suppliers/new.html.erb
<h1>Novo Fornecedor</h1>

<%if (@supplier.errors.any?)%> 
    <p>Verifique os erros abaixo:</p>
    <ul>
        <%@supplier.errors.full_messages.each do |msg|%>
            <li><%=msg%>.</li>
        <%end%>
    </ul>
<%end%> 

<%=form_with(model: @supplier) do |f|%>
    <div>
        <%=f.label :corporate_name%>
        <%=f.text_field :corporate_name%>
    </div>
    <div>
        <%=f.label :brand_name%>
        <%=f.text_area :brand_name%>
    </div>
    <div>
        <%=f.label :registration_number%>
        <%=f.text_field :registration_number%>
    </div>
    <div>
        <%=f.label :full_address%>
        <%=f.text_field :full_address%>
    </div>
    <div>
        <%=f.label :city%>
        <%=f.text_field :city%>
    </div>
    <div>
        <%=f.label :state%>
        <%=f.text_field :state%>
    </div>
    <div>
        <%=f.label :email%>
        <%=f.number_field :email%>
    </div>
    <div>
        <%=f.submit 'Enviar'%>
    </div>
<%end%>

app/views/suppliers/show.html.erb
<h1><%= @supplier.brand_name%></h1>
<h2><%= @supplier.corporate_name%></h2>

<dl>
  <dt>Documento: </dt>
  <dd><%= @supplier.registration_number%></dd>
  <dt>Endereço: </dt>
  <dd><%= @supplier.full_address%> - <%= @supplier.city%> - <%= @supplier.state%></dd>
  <dt>E-mail: </dt>
  <dd><%= @supplier.email%></dd>
</dl>

<div>
  <%=link_to('Editar', edit_supplier_path(@supplier))%>
</div>
<div>
  <%=link_to('Voltar', root_path)%>
</div>

app/views/warehouses/_form.html.erb
<%=form_with(model: @warehouse) do |f|%>
    <div>
        <%=f.label :name%>
        <%=f.text_field :name%>
    </div>
    <div>
        <%=f.label :description%>
        <%=f.text_area :description%>
    </div>
    <div>
        <%=f.label :code%>
        <%=f.text_field :code%>
    </div>
    <div>
        <%=f.label :address%>
        <%=f.text_field :address%>
    </div>
    <div>
        <%=f.label :city%>
        <%=f.text_field :city%>
    </div>
    <div>
        <%=f.label :zip_code%>
        <%=f.text_field :zip_code%>
    </div>
    <div>
        <%=f.label :area%>
        <%=f.number_field :area%>
    </div>
    <div>
        <%=f.submit 'Enviar'%>
    </div>
<%end%>

app/views/warehouses/edit.html.erb
<h1>Editar Galpão</h1>

<%= render 'form'%>

app/views/warehouses/new.html.erb
<h1>Novo Galpão</h1>

<%if (@warehouse.errors.any?)%> 
    <p>Verifique os erros abaixo:</p>
    <ul>
        <%@warehouse.errors.full_messages.each do |msg|%>
            <li><%=msg%>.</li>
        <%end%>
    </ul>
<%end%> 

<%= render 'form'%>

app/views/warehouses/show.html.erb
<h1>Galpão <%=@warehouse.code%></h1>
<h2><%=@warehouse.description%></h2>
<div>
    <strong>Nome: </strong><%=@warehouse.name%>
    <strong>Cidade: </strong><%=@warehouse.city%>
    <strong>Área: </strong><%=@warehouse.area%> m²
    <strong>Endereço: </strong><%=@warehouse.address%> <strong>CEP: </strong><%=@warehouse.zip_code%>
</div>

<div>
    <%=link_to('Editar', edit_warehouse_path(@warehouse))%>
    <%=button_to('Remover', warehouse_path(@warehouse.id), method: :delete)%>
</div>
<div>
    <%=link_to('Voltar', root_path)%>
</div>